#ifndef DISPLAY_CONSTANTS_H
#define DISPLAY_CONSTANTS_H

#define DISPLAY_WIDTH 480
#define DISPLAY_HEIGHT 320

// Title Constants
#define NAME_X 240
#define NAME_Y 19

// Select screen constants
#define COORD_DIGITS 4
#define RAD_DIGITS 0
#define COORDS_Y 52
#define RADIUS_Y 77
#define START_INSTRUCTION_X_OFFSET 50
#define NEXT_INSTRUCTION_X_OFFSET 20
#define SELECT_INSTRUCTION_Y 285
#define FILTER_CURSOR_X 5
#define FILTER_CURSOR_Y 110

// ROUTE CONSTANTS
#define ROUTE_START_Y 55
#define ROUTE_BUTTON_HEIGHT 30
#define ROUTE_PADDING 16
#define ROUTE_TEXT_Y_OFFSET 5
#define ROUTE_GAP 6

// DEPARTURE CONSTANTS
#define DEPARTURES_START_Y 100
#define DEPARTURES_ROW_HEIGHT 30
#define DEPARTURES_ROW_SPACING 12
#define DEPARTURES_TEXT_Y_OFFSET 3
#define DEPARTURES_MAX_LINE_BUTTON_WIDTH 100
#define DEPARTURES_MIN_PADDING 4

#define COL_LINE_CENTER_X 55      // Center X-point for the first column (e.g., (15 + 80/2))
#define COL_DIRECTION_X 115
#define COL_MINS_X 465

#endif